# Generated by Django 4.2.3 on 2023-07-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoItem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoitem',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
